[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://pagead2.googlesyndication.com https://googleads.g.doubleclick.net https://www.googletagmanager.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data:;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.googlesyndication.com https://factfrenzy.info https://ep1.adtrafficquality.google;
      frame-src 'self' https://googlesyndication.com https://pagead2.googlesyndication.com https://tpc.googlesyndication.com https://googleads.g.doubleclick.net https://g.doubleclick.net https://pubads.g.doubleclick.net https://partner.googleadservices.com https://www.google.com;
    """
